# Generated by Django 4.2.8 on 2024-02-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_item_image_alter_item_bought_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gst_applied',
        ),
    ]
